import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Tuple, Dict, Any, Optional


class BaseLoss(nn.Module):
    """
    Abstract Base Class for loss functions.
    """
    def __init__(self) -> None:
        super().__init__()

    def forward(self, output_dict: dict, target_dict: dict, epoch: int = 1) -> torch.Tensor:
        raise NotImplementedError("Method 'forward' must be implemented in subclasses.")


class ClipCELoss(BaseLoss):
    """
    Standard Multi-class Cross Entropy Loss at the clip level.
    """
    def forward(self, output_dict: dict, target_dict: dict, epoch: int = 1) -> torch.Tensor:
        logits = output_dict['clipwise_output']
        targets = target_dict['target']
        if targets.ndim > 1 and targets.size(-1) > 1:
            return F.cross_entropy(logits, targets)
        return F.cross_entropy(logits, targets.long())


class KDLoss(nn.Module):
    """
    Knowledge Distillation KL-Divergence Loss (Hinton et al.).
    Computes KL divergence between softened teacher probabilities and softened student log-probabilities.
    """
    def __init__(self, temperature: float = 3.0) -> None:
        super().__init__()
        self.temperature = float(temperature)

    def forward(self, student_logits: torch.Tensor, teacher_logits: torch.Tensor, reduction: str = 'batchmean') -> torch.Tensor:
        T = self.temperature
        p_student = F.log_softmax(student_logits / T, dim=-1)
        p_teacher = F.softmax(teacher_logits / T, dim=-1)
        if reduction == 'none':
            return F.kl_div(p_student, p_teacher, reduction='none').sum(dim=-1) * (T ** 2)
        return F.kl_div(p_student, p_teacher, reduction=reduction) * (T ** 2)


class AttentionTransferLoss(nn.Module):
    """
    Activation-based Attention Transfer Loss (Zagoruyko & Komodakis, ICLR 2017).
    Distills spatial attention heatmaps generated by summing squared channel activations:
        A(F) = sum_{c=1}^C |F_c|^p, normalized by L2 Frobenius norm.
    Penalizes discrepancy between student and teacher spatial attention distributions.
    """
    def __init__(self, p: int = 2, eps: float = 1e-6) -> None:
        super().__init__()
        self.p = p
        self.eps = eps

    def forward(self, student_feat_map: torch.Tensor, teacher_feat_map: torch.Tensor) -> torch.Tensor:
        """
        Args:
            student_feat_map: [B, C_s, H_s, W_s] (e.g. ConvNeXt-Nano [B, 384, 7, 7])
            teacher_feat_map: [B, C_t, H_t, W_t] (e.g. DenseNet121 [B, 1024, 7, 7])
        Returns:
            Scalar MSE loss between L2-normalized spatial attention maps.
        """
        # 1. Compute spatial attention map across channels: A = sum_c |F_c|^p
        a_s = torch.sum(torch.abs(student_feat_map) ** self.p, dim=1)  # [B, H_s, W_s]
        a_t = torch.sum(torch.abs(teacher_feat_map) ** self.p, dim=1)  # [B, H_t, W_t]

        # 2. Align spatial dimensions if they differ
        if a_s.shape[-2:] != a_t.shape[-2:]:
            a_s = F.interpolate(
                a_s.unsqueeze(1),
                size=a_t.shape[-2:],
                mode='bilinear',
                align_corners=False
            ).squeeze(1)

        # 3. L2-normalize spatial maps per sample
        b = a_s.size(0)
        a_s_flat = a_s.view(b, -1)
        a_t_flat = a_t.view(b, -1)

        a_s_norm = a_s_flat / (torch.norm(a_s_flat, p=2, dim=-1, keepdim=True) + self.eps)
        a_t_norm = a_t_flat / (torch.norm(a_t_flat, p=2, dim=-1, keepdim=True) + self.eps)

        # 4. Normalized MSE loss
        return F.mse_loss(a_s_norm, a_t_norm.detach())


class FeatureEmbeddingKDLoss(nn.Module):
    """
    Penultimate Representation Embedding Distillation.
    Projects student features (e.g. 224-dim) to teacher dimension (1024 for video, 512 for audio)
    via a lightweight training-only projection adapter, and minimizes Cosine Dissimilarity.
    """
    def __init__(self, in_dim: int, teacher_dim: int) -> None:
        super().__init__()
        self.proj = nn.Sequential(
            nn.Linear(in_dim, teacher_dim),
            nn.GELU(),
            nn.Linear(teacher_dim, teacher_dim)
        )

    def forward(self, student_feat: torch.Tensor, teacher_feat: torch.Tensor) -> torch.Tensor:
        """
        Args:
            student_feat: [B, in_dim] (e.g. [B, 224])
            teacher_feat: [B, teacher_dim] (e.g. [B, 1024] or [B, 512])
        Returns:
            Scalar Cosine embedding loss: 1.0 - CosineSimilarity
        """
        s_proj = self.proj(student_feat)
        t_feat = teacher_feat.detach()
        cos_sim = F.cosine_similarity(s_proj, t_feat, dim=-1)
        return torch.mean(1.0 - cos_sim)


class PairwiseTournamentLoss(BaseLoss):
    """
    Hierarchical Pairwise Cross-Boundary Tournament Loss with Multi-Level Dual-Teacher Knowledge Distillation (KD).
    Optimizes 3-level tournament decision:
      Level 1: Activity Gating Loss (None vs Active Feeding).
      Level 2: 3 Pairwise Cross-Boundary Losses (B12: Weak vs Medium, B23: Medium vs Strong, B13: Weak vs Strong).
      Level 3: End-to-End Multi-Class Cross Entropy on final tournament voting probabilities.
    Plus Independent Unimodal Multi-Level Supervision & Knowledge Distillation:
      - Video Backbone Logits: (1 - a_v) * CE + a_v * KD_video (Teacher: DenseNet121, default 35% CE / 65% KD)
      - Audio Backbone Logits: (1 - a_a) * CE + a_a * KD_audio (Teacher: PANNS_Cnn6, default 35% CE / 65% KD)
      - Intermediate Spatial Attention Transfer: Stage 4 ConvNeXt-Nano (384x7x7) <- DenseNet121 (1024x7x7)
      - Penultimate Feature Embedding Distillation: Student (224-dim) <- Teacher (1024-dim / 512-dim) via Cosine Alignment
    """
    def __init__(
        self,
        weight_act: float = 0.5,
        weight_pairwise: float = 0.5,
        weight_ce: float = 1.0,
        aux_loss_weight: float = 0.3,
        weight_video_loss: Optional[float] = None,
        weight_audio_loss: Optional[float] = None,
        enable_kd: bool = True,
        kd_temperature_video: float = 3.0,
        kd_temperature_audio: float = 2.0,
        kd_alpha_video: float = 0.60,
        kd_alpha_audio: float = 0.60,
        weight_feature_kd: float = 0.2,
        weight_at_kd: float = 0.2,
        enable_feature_kd: bool = True,
        enable_at_kd: bool = True,
        adaptive_kd: bool = False,
        adaptive_kd_min_alpha: float = 0.0,
        student_feat_v_dim: int = 224,
        teacher_feat_v_dim: int = 1024,
        student_feat_a_dim: int = 224,
        teacher_feat_a_dim: int = 512,
        only_backbones: bool = False,
        **kwargs
    ) -> None:
        super().__init__()
        self.weight_act = float(kwargs.get("weight_act", weight_act))
        self.weight_pairwise = float(kwargs.get("weight_pairwise", weight_pairwise))
        self.weight_ce = float(kwargs.get("weight_ce", weight_ce))
        default_aux = float(kwargs.get("aux_loss_weight", aux_loss_weight))
        self.weight_v = float(kwargs.get("weight_video_loss", weight_video_loss if weight_video_loss is not None else default_aux))
        self.weight_a = float(kwargs.get("weight_audio_loss", weight_audio_loss if weight_audio_loss is not None else default_aux))

        # Multi-Level Knowledge Distillation Configuration
        self.enable_kd = bool(kwargs.get("enable_kd", enable_kd))
        self.kd_alpha_v = float(kwargs.get("kd_alpha_video", kd_alpha_video))
        self.kd_alpha_a = float(kwargs.get("kd_alpha_audio", kd_alpha_audio))
        self.adaptive_kd = bool(kwargs.get("adaptive_kd", adaptive_kd))
        self.adaptive_kd_min_alpha = float(kwargs.get("adaptive_kd_min_alpha", adaptive_kd_min_alpha))

        self.kd_loss_video = KDLoss(temperature=float(kwargs.get("kd_temperature_video", kd_temperature_video)))
        self.kd_loss_audio = KDLoss(temperature=float(kwargs.get("kd_temperature_audio", kd_temperature_audio)))

        self.enable_feature_kd = bool(kwargs.get("enable_feature_kd", enable_feature_kd))
        self.enable_at_kd = bool(kwargs.get("enable_at_kd", enable_at_kd))
        self.weight_feat = float(kwargs.get("weight_feature_kd", weight_feature_kd))
        self.weight_at = float(kwargs.get("weight_at_kd", weight_at_kd))

        if self.enable_kd and self.enable_at_kd:
            self.at_loss = AttentionTransferLoss(p=2)
        else:
            self.at_loss = None

        if self.enable_kd and self.enable_feature_kd:
            self.feat_kd_v = FeatureEmbeddingKDLoss(in_dim=student_feat_v_dim, teacher_dim=teacher_feat_v_dim)
            self.feat_kd_a = FeatureEmbeddingKDLoss(in_dim=student_feat_a_dim, teacher_dim=teacher_feat_a_dim)
        else:
            self.feat_kd_v = None
            self.feat_kd_a = None

        self.last_mean_alpha_v: float = self.kd_alpha_v
        self.last_mean_alpha_a: float = self.kd_alpha_a
        self.only_backbones = bool(kwargs.get("only_backbones", only_backbones))

    def _get_raw_targets(self, targets: torch.Tensor) -> torch.Tensor:
        if targets.ndim > 1 and targets.size(-1) > 1:
            y_raw = targets.argmax(dim=-1)
        else:
            y_raw = targets.long().squeeze()
            if y_raw.ndim == 0:
                y_raw = y_raw.unsqueeze(0)
        return y_raw

    def forward(self, output_dict: dict, target_dict: dict, epoch: int = 1) -> torch.Tensor:
        targets = target_dict['target']
        y_raw = self._get_raw_targets(targets)  # [B]: 0=None, 1=Strong, 2=Medium, 3=Weak

        # 1. Video Backbone Auxiliary / Distillation Loss (Logits: Adaptive or Fixed 35% CE / 65% KD)
        logits_v = output_dict.get("logits_video")
        t_logits_v = target_dict.get("teacher_logits_video")
        if logits_v is not None:
            if self.enable_kd and t_logits_v is not None:
                if self.adaptive_kd:
                    ce_v_sample = F.cross_entropy(logits_v, y_raw, reduction='none')
                    kd_v_sample = self.kd_loss_video(logits_v, t_logits_v, reduction='none')
                    with torch.no_grad():
                        p_tea_v = F.softmax(t_logits_v, dim=-1)
                        pred_tea_v = p_tea_v.argmax(dim=-1)
                        conf_tea_v = p_tea_v.gather(dim=-1, index=y_raw.unsqueeze(-1)).squeeze(-1)
                        correct_mask_v = (pred_tea_v == y_raw).float()
                        alpha_v_sample = torch.where(
                            correct_mask_v > 0.5,
                            torch.clamp(self.kd_alpha_v * conf_tea_v, min=self.adaptive_kd_min_alpha, max=self.kd_alpha_v),
                            torch.full_like(conf_tea_v, self.adaptive_kd_min_alpha)
                        )
                    loss_v = torch.mean((1.0 - alpha_v_sample) * ce_v_sample + alpha_v_sample * kd_v_sample)
                    self.last_mean_alpha_v = float(alpha_v_sample.mean().item())
                else:
                    ce_v = F.cross_entropy(logits_v, y_raw)
                    kd_v = self.kd_loss_video(logits_v, t_logits_v, reduction='batchmean')
                    loss_v = (1.0 - self.kd_alpha_v) * ce_v + self.kd_alpha_v * kd_v
                    self.last_mean_alpha_v = self.kd_alpha_v
            else:
                loss_v = F.cross_entropy(logits_v, y_raw)
        else:
            loss_v = torch.tensor(0.0, device=targets.device)

        # 2. Audio Backbone Auxiliary / Distillation Loss (Logits: Adaptive or Fixed 35% CE / 65% KD)
        logits_a = output_dict.get("logits_audio")
        t_logits_a = target_dict.get("teacher_logits_audio")
        if logits_a is not None:
            if self.enable_kd and t_logits_a is not None:
                if self.adaptive_kd:
                    ce_a_sample = F.cross_entropy(logits_a, y_raw, reduction='none')
                    kd_a_sample = self.kd_loss_audio(logits_a, t_logits_a, reduction='none')
                    with torch.no_grad():
                        p_tea_a = F.softmax(t_logits_a, dim=-1)
                        pred_tea_a = p_tea_a.argmax(dim=-1)
                        conf_tea_a = p_tea_a.gather(dim=-1, index=y_raw.unsqueeze(-1)).squeeze(-1)
                        correct_mask_a = (pred_tea_a == y_raw).float()
                        alpha_a_sample = torch.where(
                            correct_mask_a > 0.5,
                            torch.clamp(self.kd_alpha_a * conf_tea_a, min=self.adaptive_kd_min_alpha, max=self.kd_alpha_a),
                            torch.full_like(conf_tea_a, self.adaptive_kd_min_alpha)
                        )
                    loss_a = torch.mean((1.0 - alpha_a_sample) * ce_a_sample + alpha_a_sample * kd_a_sample)
                    self.last_mean_alpha_a = float(alpha_a_sample.mean().item())
                else:
                    ce_a = F.cross_entropy(logits_a, y_raw)
                    kd_a = self.kd_loss_audio(logits_a, t_logits_a, reduction='batchmean')
                    loss_a = (1.0 - self.kd_alpha_a) * ce_a + self.kd_alpha_a * kd_a
                    self.last_mean_alpha_a = self.kd_alpha_a
            else:
                loss_a = F.cross_entropy(logits_a, y_raw)
        else:
            loss_a = torch.tensor(0.0, device=targets.device)

        # 3. Intermediate Feature Map Distillation: Spatial Attention Transfer (7x7)
        loss_at = torch.tensor(0.0, device=targets.device)
        if self.enable_kd and self.enable_at_kd and self.at_loss is not None:
            feat_map_v = output_dict.get("feat_map_video")
            t_feat_map_v = target_dict.get("teacher_feat_map_video")
            if feat_map_v is not None and t_feat_map_v is not None:
                loss_at = self.at_loss(feat_map_v, t_feat_map_v)

        # 4. Penultimate Feature Embedding Distillation (Cosine Similarity)
        loss_feat = torch.tensor(0.0, device=targets.device)
        if self.enable_kd and self.enable_feature_kd:
            feat_v = output_dict.get("feat_video")
            t_feat_v = target_dict.get("teacher_feat_video")
            loss_fv = torch.tensor(0.0, device=targets.device)
            if feat_v is not None and t_feat_v is not None and self.feat_kd_v is not None:
                loss_fv = self.feat_kd_v(feat_v, t_feat_v)

            feat_a = output_dict.get("feat_audio")
            t_feat_a = target_dict.get("teacher_feat_audio")
            loss_fa = torch.tensor(0.0, device=targets.device)
            if feat_a is not None and t_feat_a is not None and self.feat_kd_a is not None:
                loss_fa = self.feat_kd_a(feat_a, t_feat_a)

            loss_feat = 0.5 * (loss_fv + loss_fa)

        if self.only_backbones:
            # Phase 1 mode (if two-phase warmup is used)
            return loss_v + loss_a + self.weight_feat * loss_feat + self.weight_at * loss_at

        # 5. Level 1: Feeding Activity Gating Loss (None=0 vs Feeding=1)
        logit_act = output_dict.get("logit_act")
        if logit_act is not None:
            target_act = (y_raw != 0).float()
            loss_act = F.binary_cross_entropy_with_logits(logit_act, target_act)
        else:
            loss_act = torch.tensor(0.0, device=targets.device)

        # 6. Level 2: 3 Pairwise Cross-Boundary Head Losses
        logit_12 = output_dict.get("logit_12")  # Positive -> Weak, Negative -> Medium
        logit_23 = output_dict.get("logit_23")  # Positive -> Medium, Negative -> Strong
        logit_13 = output_dict.get("logit_13")  # Positive -> Weak, Negative -> Strong

        # B12: Weak (3) vs Medium (2)
        mask_12 = (y_raw == 3) | (y_raw == 2)
        if mask_12.sum() > 0 and logit_12 is not None:
            target_12 = (y_raw[mask_12] == 3).float()  # 1.0 if Weak, 0.0 if Medium
            loss_12 = F.binary_cross_entropy_with_logits(logit_12[mask_12], target_12)
        else:
            loss_12 = torch.tensor(0.0, device=targets.device)

        # B23: Medium (2) vs Strong (1)
        mask_23 = (y_raw == 2) | (y_raw == 1)
        if mask_23.sum() > 0 and logit_23 is not None:
            target_23 = (y_raw[mask_23] == 2).float()  # 1.0 if Medium, 0.0 if Strong
            loss_23 = F.binary_cross_entropy_with_logits(logit_23[mask_23], target_23)
        else:
            loss_23 = torch.tensor(0.0, device=targets.device)

        # B13: Weak (3) vs Strong (1) [Cross-Protection Boundary]
        mask_13 = (y_raw == 3) | (y_raw == 1)
        if mask_13.sum() > 0 and logit_13 is not None:
            target_13 = (y_raw[mask_13] == 3).float()  # 1.0 if Weak, 0.0 if Strong
            loss_13 = F.binary_cross_entropy_with_logits(logit_13[mask_13], target_13)
        else:
            loss_13 = torch.tensor(0.0, device=targets.device)

        loss_pairwise = (loss_12 + loss_23 + loss_13) / 3.0

        # 7. Level 3: Multi-class Cross Entropy on Final Logits
        logits = output_dict.get("clipwise_output", output_dict.get("logits"))
        if logits is not None:
            loss_ce = F.cross_entropy(logits, y_raw)
        else:
            loss_ce = torch.tensor(0.0, device=targets.device)

        # Total Composite Tournament Loss + Multi-Level Dual-Teacher KD
        total_loss = (
            self.weight_ce * loss_ce +
            self.weight_act * loss_act +
            self.weight_pairwise * loss_pairwise +
            self.weight_v * loss_v +
            self.weight_a * loss_a +
            self.weight_feat * loss_feat +
            self.weight_at * loss_at
        )

        return total_loss


# Backward compatibility aliases
BilateralBoundaryLoss = PairwiseTournamentLoss
OrdinalWassersteinEvidentialLoss = PairwiseTournamentLoss
TMCEvidentialLoss = PairwiseTournamentLoss
